- params:
    git:
      repoName: yarn-test
      branches:
        - main
    scan:
      failOnSecurityIssues: false
      projects:
        - installCommand: "yarn install"
          workingDirs:
            - "."
